export const Constants = () =>{
    return{
        ADAPTER: "ACBS_INFOS",
        SERVER: "http://10.64.250.149:80/",//"http://192.168.1.222:80/",
        HOSE_Stocks :["AAA","AAM","AAT","ABS","ACB","ACC","ACL"],
        FIELD_DEF: ["CODE","BASIC_PRICE","CEILING_PRICE","FLOOR_PRICE","BPRICE3","BQTTY3","BPRICE2","BQTTY2","BPRICE1","BQTTY1","MATCH_PRICE","CHANGE","p","MATCH_QTTY","TOTAL_TRADED_QTTY","TOTAL_TRADED_VALUE","SPRICE1","SQTTY1","SPRICE2","SQTTY2","SPRICE3","SQTTY3","AVERAGE_PRICE","HIGHEST_PRICE","LOWEST_PRICE","BUY_FOREIGN_QTTY","SELL_FOREIGN_QTTY","CURRENT_ROOM","ISSUER_NAME","LAST_TRADING_DATE","BASE_PRICE_W","EXERCISE_PRICE","EXERCISE_RATIO","BASE_DEVIATION","POINT_CAPITAL","CEILING_PRICE_W","FLOOR_PRICE_W","BASIC_PRICE_W"],
    };
}